version: "3"

services:
  gfwlist2dnsmasq:
    build:
      context: .
    image: swr.cn-east-2.myhuaweicloud.com/mingcheng/gfwlist2dnsmasq
    entrypoint:
      - /bin/gfwlist2dnsmasq
    environment:
      TZ: "Asia/Shanghai"
      SOCKS5_PROXY: "172.16.1.254:1087"
      GFW_LIST: "https://pagure.io/gfwlist/raw/master/f/gfwlist.txt"
    dns:
      - 8.8.8.8
    volumes:
      - ./conf:/etc/dnsmasq.d/
    restart: on-failure
